# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'del_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_del_form(object):
    def setupUi(self, del_form):
        del_form.setObjectName("del_form")
        del_form.resize(312, 171)
        self.lineEdit = QtWidgets.QLineEdit(del_form)
        self.lineEdit.setGeometry(QtCore.QRect(70, 80, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(del_form)
        self.label.setGeometry(QtCore.QRect(90, 40, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setToolTipDuration(-1)
        self.label.setObjectName("label")

        self.retranslateUi(del_form)
        QtCore.QMetaObject.connectSlotsByName(del_form)

    def retranslateUi(self, del_form):
        _translate = QtCore.QCoreApplication.translate
        del_form.setWindowTitle(_translate("del_form", "Удаление элемента"))
        self.label.setText(_translate("del_form", "Введите id элемента"))
